[package]
name = "rust" # Appears in the filename of the compiled dynamic library.
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
fluent = "0.16.0"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["experimental-threads", "custom-godot"] }
unic-langid = "0.9.4"